### PR TITLE
Docker update

### LINKED ISSUE #3: Add automated test on Dockerfile

### LINKED ISSUE #21: Add `zip` to docker environment
Please add `zip` to the docker environment.  So we can use the deploy script

### LINKED ISSUE #22: Add `net-tools` to docker environment
We suggest to students to use `netstat` which requires installing `net-tools` with sudo permissions.  Some students are scared to modify the docker environment, so we should just install this for them from the get-go.

>The demo is showing how to use "netstat" to see ports in use, etc. When I tried to run this, I received a message that "netstat: command not found."
> 
> Based on an internet search, I tried installing netstat with 
>
>$ sudo apt update
>$ sudo apt install net-tools
>
>The terminal then asked for a password for cit595. I didn't recall setting any ubuntu password, and was nervous about trying to reset docker. 
>
>Any suggestions?

### PR DESCRIPTION
**Pull request by alesparza**
Adds some more applications (e.g. net-tools).

Adds a script to test that the installs are present (add to project0 instructions?)

Reorganized docker setup script

### CODE REVIEW

**Comment by alesparza** [comment]
See the new image [here](https://hub.docker.com/r/cis548/docker-env/tags).

You can download it with 

```
docker pull cis548/docker-env:docker.update
```

**Comment by rachel-friend** [comment]
@alesparza when I look at the new image, the one tagged as latest was being pushed 12 hours ago and another one tagged as update was pushed 2 hours ago. Does that matter? Are these the same? I see the download is the same.

**Comment by alesparza** [comment]
> @alesparza when I look at the new image, the one tagged as latest was being pushed 12 hours ago and another one tagged as update was pushed 2 hours ago. Does that matter? Are these the same? I see the download is the same.

Err... I must have pushed the new version as latest.  I can push the old version back to latest.  The one for docker-setup is definitely the new one though

**Comment by alesparza** [comment]
> > @alesparza when I look at the new image, the one tagged as latest was being pushed 12 hours ago and another one tagged as update was pushed 2 hours ago. Does that matter? Are these the same? I see the download is the same.
> 
> Err... I must have pushed the new version as latest. I can push the old version back to latest. The one for docker-setup is definitely the new one though

Actually I think it is correct.  I think I re-pushed the latest from the 1.1 release here and docker.update is slightly larger (the additional items are only a few kilobytes).  So I think they are correct.

If you pull latest, it should not have the test build script and you won't be able to use netstat.  But docker.update should be able to do those things

**Comment by rachel-friend** [comment]
Got it, thanks!

**Review by rachel-friend — APPROVED** [review]
This is great. All the new tools worked after I cloned and mounted like you said.

**Review by dianehoffstetterupenn — APPROVED** [review]
Looks good.

**Pull request merged**
